name: Build and deploy bike-history database

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Setup ssh
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{secrets.SSH_HOST}}

      - uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          cd /tmp 
          wget https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64 -O docker-compose
          chmod 700 docker-compose

      - name: Deploy to Docker Host
        run: |
          echo '${{secrets.MAIL_SECRETS}}' >> ./src/config/smtp.json
          echo '${{secrets.KEYS_SECRETS}}' >> ./src/config/keys.json
          /tmp/docker-compose -H ssh://${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} up --build -d
